log_path: metadata.log
pipeline:
  import: ["input", "database", "output"]
  query: ["query", "output"]
input:
  exit_on_error: false
  file_exts: [] # empty => read all files
  meta_confg: "metadata.yml"
  tags_to_load: [] # empty => load all tags
  timezone: Asia/Singapore
database:
  name: metadata
  uri: "mongodb://localhost:27017"
  drop_first: false
output:
  cols: ["FileName", "Make", "Model", "DateTimeOriginal"]
  path: metadata.csv
  type: csv
verbose: true
